completed task 15
frostmark/railway_ror pull request #1
Opened 2017-05-25 08:46 UTC by frostmark

2017-05-25 19:01 UTC, iBublik requested changes

2017-05-25 19:01 UTC, iBublik commented on app/views/trains/show.html.erb
> +  <%= @carriages.where(kind: :coupe).count %>
Запрос, конечно, простой, но лучше даже его вынести в метод модели - вьюхи должны быть максимально "тупыми"

2017-05-25 19:01 UTC, iBublik commented on app/views/trains/show.html.erb
> +  <% @carriages.each do |carriage| %>
Нам нужно не список вагонов выводить, а общее число верхних/нижних мест с разделением на типы вагонов (помни, что логики во вьюхах быть не должно)

2017-05-26 08:29 UTC, vkurennov approved these changes

2017-05-26 08:48 UTC, merged