Task17
frostmark/railway_ror pull request #3
Opened 2017-06-11 17:19 UTC by frostmark

2017-06-11 18:04 UTC, iBublik requested changes

2017-06-11 18:04 UTC, iBublik commented on app/controllers/carriages_controller.rb
>  class CarriagesController < ApplicationController
Привязка вагона к поезду теперь должна происходить с помощью параметра из роута, а не из формы (не забудь убрать его из `permit`)

2017-06-11 18:04 UTC, iBublik commented on db/migrate/20170611144549_add_arrive_departure_time_to_routes_stations.rb
> +    add_column :routes_stations, :arrive_time, :time
Когда изменения вносятся в одну таблицу, лаконичнее использовать `change_table`

2017-06-11 18:04 UTC, iBublik commented on app/controllers/stations_controller.rb
> +
Не хватает экшена для обновления времени прибытия/отправления

2017-06-11 18:04 UTC, iBublik commented on app/views/routes/show.html.erb
> +              <%= form_tag update_position_station_path(station), method: :patch do %>
Тут еще нужна форма для обновления времени прибытия/отправления

2017-06-11 18:04 UTC, iBublik commented on app/models/route.rb
> +    routes = with_start_station.merge(with_end_station)
Не похоже, что это работает. Будет применено последнее условие - т.е. будут выбраны маршруты, у которых есть 2я станция. Можно попробовать реализовать такой запрос, но проще конечно выбрать маршруты с первой станцией, потом маршруты со второй, и на Ruby получить пересечение этих множеств

2017-06-11 18:04 UTC, iBublik commented on app/models/route.rb
> +      if [start_station_number, end_station_number].all?
Не сразу понял что здесь происходит. Проще воспринимать условие `if start_station && end_station`

2017-06-11 18:04 UTC, iBublik commented on app/controllers/tickets_controller.rb
> +    redirect_to :search unless [@start_station, @end_station, @route].all?
Возможно это лично моя проблема, но как-то тяжело видеть `all?` без критерия успешности :) Я бы писал `all?(&:present?)` - заодно будут отсечены пустые значения

2017-06-12 17:16 UTC, frostmark commented on app/models/route.rb
> +    routes = with_start_station.merge(with_end_station)
@iBublik Это работает)

2017-06-12 17:55 UTC, iBublik commented on app/models/route.rb
> +    routes = with_start_station.merge(with_end_station)
@frostmark я развернул проект локально. Допустим ты передал в метод значения 1 и 2 . Эта строка `with_start_station.merge(with_end_station)` выдает примерно такой запрос:
```SQL
SELECT routes.id, ...
FROM routes LEFT OUTER JOIN route_stations ON route_stations.station_id = routes.id
WHERE route_stations.station_id = 2
```
Обрати внимание, что запрос на station_id всего одни, при этом он на последний переданный id. Это из-за merge происходит.
А работает у тебя потому что ты далее в цикле снова начинаешь шерстить станции маршрута. И если уже там не нашлось начальной станции, мы отбрасываем данный маршрут. Твой алгоритм ищет маршруты с конечной станцией, а потом в цикле проверяет есть ли в них начальная.

2017-06-12 18:13 UTC, frostmark commented on app/models/route.rb
> +    routes = with_start_station.merge(with_end_station)
@iBublik Понял, спасибо

2017-06-12 19:06 UTC, iBublik commented on app/models/route.rb
> +    routes = with_start_station.merge(with_end_station)
@frostmark Лучше поправь. А то получается есть логическая ошибка, которая нивелируется в другом месте.

2017-06-13 02:49 UTC, frostmark commented on app/models/route.rb
> +    routes = with_start_station.merge(with_end_station)
@iBublik ага, исправлю

2017-06-13 07:51 UTC, vkurennov requested changes

2017-06-13 07:51 UTC, vkurennov commented on app/controllers/carriages_controller.rb
>      @carriage = Carriage.new(carriage_params)
Можно сразу: `@carriage = @train.carriages.new(carriage_params)`

2017-06-13 07:51 UTC, vkurennov commented on app/models/route.rb
> +    routes = with_start_station.merge(with_end_station)
Поддерживаю @iBublik, но пока не вижу исправления. В merge, конечно же, происходит "затирание" параметров.

2017-06-13 07:51 UTC, vkurennov commented on app/controllers/tickets_controller.rb
> +    params.require(:ticket).permit(:name, :passport, :start_station_id, :end_station_id, :route_id, :train_id, :user_id)
У тебя tickets вложен в train, это значит, что train_id не должен передаваться в форме, т.к. он передается в url. кроме того, связь с поездом должна устанавливаться в create в таком случае

2017-06-13 14:22 UTC, vkurennov approved these changes

2017-06-13 14:59 UTC, merged